// Code generated by internal/page/gen; DO NOT EDIT.

package page

import "unsafe"

// ptrObject is the object of a Fixed page whose values are a word with a
// pointer: J words of head and remainder (H), then the values (V).
type ptrObject[T any, H, V any] struct {
	h H
	v V
}

// allocPtr returns a zeroed object of class c whose first j words are no
// pointers and whose other words are values of T, a word with a pointer. It
// returns nil for a class or a j that no page has.
func allocPtr[T any](c, j int) unsafe.Pointer {
	switch c {
	case 0:
		switch j {
		case 1:
			return unsafe.Pointer(new(ptrObject[T, [1]uint64, [3]T]))
		case 2:
			return unsafe.Pointer(new(ptrObject[T, [2]uint64, [2]T]))
		case 3:
			return unsafe.Pointer(new(ptrObject[T, [3]uint64, [1]T]))
		}
	case 1:
		switch j {
		case 1:
			return unsafe.Pointer(new(ptrObject[T, [1]uint64, [7]T]))
		case 2:
			return unsafe.Pointer(new(ptrObject[T, [2]uint64, [6]T]))
		case 3:
			return unsafe.Pointer(new(ptrObject[T, [3]uint64, [5]T]))
		case 4:
			return unsafe.Pointer(new(ptrObject[T, [4]uint64, [4]T]))
		case 5:
			return unsafe.Pointer(new(ptrObject[T, [5]uint64, [3]T]))
		case 6:
			return unsafe.Pointer(new(ptrObject[T, [6]uint64, [2]T]))
		case 7:
			return unsafe.Pointer(new(ptrObject[T, [7]uint64, [1]T]))
		}
	case 2:
		switch j {
		case 1:
			return unsafe.Pointer(new(ptrObject[T, [1]uint64, [15]T]))
		case 2:
			return unsafe.Pointer(new(ptrObject[T, [2]uint64, [14]T]))
		case 3:
			return unsafe.Pointer(new(ptrObject[T, [3]uint64, [13]T]))
		case 4:
			return unsafe.Pointer(new(ptrObject[T, [4]uint64, [12]T]))
		case 5:
			return unsafe.Pointer(new(ptrObject[T, [5]uint64, [11]T]))
		case 6:
			return unsafe.Pointer(new(ptrObject[T, [6]uint64, [10]T]))
		case 7:
			return unsafe.Pointer(new(ptrObject[T, [7]uint64, [9]T]))
		case 8:
			return unsafe.Pointer(new(ptrObject[T, [8]uint64, [8]T]))
		case 9:
			return unsafe.Pointer(new(ptrObject[T, [9]uint64, [7]T]))
		case 10:
			return unsafe.Pointer(new(ptrObject[T, [10]uint64, [6]T]))
		case 11:
			return unsafe.Pointer(new(ptrObject[T, [11]uint64, [5]T]))
		case 12:
			return unsafe.Pointer(new(ptrObject[T, [12]uint64, [4]T]))
		case 13:
			return unsafe.Pointer(new(ptrObject[T, [13]uint64, [3]T]))
		case 14:
			return unsafe.Pointer(new(ptrObject[T, [14]uint64, [2]T]))
		case 15:
			return unsafe.Pointer(new(ptrObject[T, [15]uint64, [1]T]))
		}
	case 3:
		switch j {
		case 1:
			return unsafe.Pointer(new(ptrObject[T, [1]uint64, [31]T]))
		case 2:
			return unsafe.Pointer(new(ptrObject[T, [2]uint64, [30]T]))
		case 3:
			return unsafe.Pointer(new(ptrObject[T, [3]uint64, [29]T]))
		case 4:
			return unsafe.Pointer(new(ptrObject[T, [4]uint64, [28]T]))
		case 5:
			return unsafe.Pointer(new(ptrObject[T, [5]uint64, [27]T]))
		case 6:
			return unsafe.Pointer(new(ptrObject[T, [6]uint64, [26]T]))
		case 7:
			return unsafe.Pointer(new(ptrObject[T, [7]uint64, [25]T]))
		case 8:
			return unsafe.Pointer(new(ptrObject[T, [8]uint64, [24]T]))
		case 9:
			return unsafe.Pointer(new(ptrObject[T, [9]uint64, [23]T]))
		case 10:
			return unsafe.Pointer(new(ptrObject[T, [10]uint64, [22]T]))
		case 11:
			return unsafe.Pointer(new(ptrObject[T, [11]uint64, [21]T]))
		case 12:
			return unsafe.Pointer(new(ptrObject[T, [12]uint64, [20]T]))
		case 13:
			return unsafe.Pointer(new(ptrObject[T, [13]uint64, [19]T]))
		case 14:
			return unsafe.Pointer(new(ptrObject[T, [14]uint64, [18]T]))
		case 15:
			return unsafe.Pointer(new(ptrObject[T, [15]uint64, [17]T]))
		case 16:
			return unsafe.Pointer(new(ptrObject[T, [16]uint64, [16]T]))
		case 17:
			return unsafe.Pointer(new(ptrObject[T, [17]uint64, [15]T]))
		case 18:
			return unsafe.Pointer(new(ptrObject[T, [18]uint64, [14]T]))
		case 19:
			return unsafe.Pointer(new(ptrObject[T, [19]uint64, [13]T]))
		case 20:
			return unsafe.Pointer(new(ptrObject[T, [20]uint64, [12]T]))
		case 21:
			return unsafe.Pointer(new(ptrObject[T, [21]uint64, [11]T]))
		case 22:
			return unsafe.Pointer(new(ptrObject[T, [22]uint64, [10]T]))
		case 23:
			return unsafe.Pointer(new(ptrObject[T, [23]uint64, [9]T]))
		case 24:
			return unsafe.Pointer(new(ptrObject[T, [24]uint64, [8]T]))
		case 25:
			return unsafe.Pointer(new(ptrObject[T, [25]uint64, [7]T]))
		case 26:
			return unsafe.Pointer(new(ptrObject[T, [26]uint64, [6]T]))
		case 27:
			return unsafe.Pointer(new(ptrObject[T, [27]uint64, [5]T]))
		case 28:
			return unsafe.Pointer(new(ptrObject[T, [28]uint64, [4]T]))
		case 29:
			return unsafe.Pointer(new(ptrObject[T, [29]uint64, [3]T]))
		case 30:
			return unsafe.Pointer(new(ptrObject[T, [30]uint64, [2]T]))
		case 31:
			return unsafe.Pointer(new(ptrObject[T, [31]uint64, [1]T]))
		}
	case 4:
		switch j {
		case 1:
			return unsafe.Pointer(new(ptrObject[T, [1]uint64, [47]T]))
		case 2:
			return unsafe.Pointer(new(ptrObject[T, [2]uint64, [46]T]))
		case 3:
			return unsafe.Pointer(new(ptrObject[T, [3]uint64, [45]T]))
		case 4:
			return unsafe.Pointer(new(ptrObject[T, [4]uint64, [44]T]))
		case 5:
			return unsafe.Pointer(new(ptrObject[T, [5]uint64, [43]T]))
		case 6:
			return unsafe.Pointer(new(ptrObject[T, [6]uint64, [42]T]))
		case 7:
			return unsafe.Pointer(new(ptrObject[T, [7]uint64, [41]T]))
		case 8:
			return unsafe.Pointer(new(ptrObject[T, [8]uint64, [40]T]))
		case 9:
			return unsafe.Pointer(new(ptrObject[T, [9]uint64, [39]T]))
		case 10:
			return unsafe.Pointer(new(ptrObject[T, [10]uint64, [38]T]))
		case 11:
			return unsafe.Pointer(new(ptrObject[T, [11]uint64, [37]T]))
		case 12:
			return unsafe.Pointer(new(ptrObject[T, [12]uint64, [36]T]))
		case 13:
			return unsafe.Pointer(new(ptrObject[T, [13]uint64, [35]T]))
		case 14:
			return unsafe.Pointer(new(ptrObject[T, [14]uint64, [34]T]))
		case 15:
			return unsafe.Pointer(new(ptrObject[T, [15]uint64, [33]T]))
		case 16:
			return unsafe.Pointer(new(ptrObject[T, [16]uint64, [32]T]))
		case 17:
			return unsafe.Pointer(new(ptrObject[T, [17]uint64, [31]T]))
		case 18:
			return unsafe.Pointer(new(ptrObject[T, [18]uint64, [30]T]))
		case 19:
			return unsafe.Pointer(new(ptrObject[T, [19]uint64, [29]T]))
		case 20:
			return unsafe.Pointer(new(ptrObject[T, [20]uint64, [28]T]))
		case 21:
			return unsafe.Pointer(new(ptrObject[T, [21]uint64, [27]T]))
		case 22:
			return unsafe.Pointer(new(ptrObject[T, [22]uint64, [26]T]))
		case 23:
			return unsafe.Pointer(new(ptrObject[T, [23]uint64, [25]T]))
		case 24:
			return unsafe.Pointer(new(ptrObject[T, [24]uint64, [24]T]))
		case 25:
			return unsafe.Pointer(new(ptrObject[T, [25]uint64, [23]T]))
		case 26:
			return unsafe.Pointer(new(ptrObject[T, [26]uint64, [22]T]))
		case 27:
			return unsafe.Pointer(new(ptrObject[T, [27]uint64, [21]T]))
		case 28:
			return unsafe.Pointer(new(ptrObject[T, [28]uint64, [20]T]))
		case 29:
			return unsafe.Pointer(new(ptrObject[T, [29]uint64, [19]T]))
		case 30:
			return unsafe.Pointer(new(ptrObject[T, [30]uint64, [18]T]))
		case 31:
			return unsafe.Pointer(new(ptrObject[T, [31]uint64, [17]T]))
		case 32:
			return unsafe.Pointer(new(ptrObject[T, [32]uint64, [16]T]))
		case 33:
			return unsafe.Pointer(new(ptrObject[T, [33]uint64, [15]T]))
		case 34:
			return unsafe.Pointer(new(ptrObject[T, [34]uint64, [14]T]))
		case 35:
			return unsafe.Pointer(new(ptrObject[T, [35]uint64, [13]T]))
		case 36:
			return unsafe.Pointer(new(ptrObject[T, [36]uint64, [12]T]))
		case 37:
			return unsafe.Pointer(new(ptrObject[T, [37]uint64, [11]T]))
		case 38:
			return unsafe.Pointer(new(ptrObject[T, [38]uint64, [10]T]))
		case 39:
			return unsafe.Pointer(new(ptrObject[T, [39]uint64, [9]T]))
		case 40:
			return unsafe.Pointer(new(ptrObject[T, [40]uint64, [8]T]))
		case 41:
			return unsafe.Pointer(new(ptrObject[T, [41]uint64, [7]T]))
		case 42:
			return unsafe.Pointer(new(ptrObject[T, [42]uint64, [6]T]))
		case 43:
			return unsafe.Pointer(new(ptrObject[T, [43]uint64, [5]T]))
		case 44:
			return unsafe.Pointer(new(ptrObject[T, [44]uint64, [4]T]))
		case 45:
			return unsafe.Pointer(new(ptrObject[T, [45]uint64, [3]T]))
		case 46:
			return unsafe.Pointer(new(ptrObject[T, [46]uint64, [2]T]))
		case 47:
			return unsafe.Pointer(new(ptrObject[T, [47]uint64, [1]T]))
		}
	case 5:
		switch j {
		case 1:
			return unsafe.Pointer(new(ptrObject[T, [1]uint64, [63]T]))
		case 2:
			return unsafe.Pointer(new(ptrObject[T, [2]uint64, [62]T]))
		case 3:
			return unsafe.Pointer(new(ptrObject[T, [3]uint64, [61]T]))
		case 4:
			return unsafe.Pointer(new(ptrObject[T, [4]uint64, [60]T]))
		case 5:
			return unsafe.Pointer(new(ptrObject[T, [5]uint64, [59]T]))
		case 6:
			return unsafe.Pointer(new(ptrObject[T, [6]uint64, [58]T]))
		case 7:
			return unsafe.Pointer(new(ptrObject[T, [7]uint64, [57]T]))
		case 8:
			return unsafe.Pointer(new(ptrObject[T, [8]uint64, [56]T]))
		case 9:
			return unsafe.Pointer(new(ptrObject[T, [9]uint64, [55]T]))
		case 10:
			return unsafe.Pointer(new(ptrObject[T, [10]uint64, [54]T]))
		case 11:
			return unsafe.Pointer(new(ptrObject[T, [11]uint64, [53]T]))
		case 12:
			return unsafe.Pointer(new(ptrObject[T, [12]uint64, [52]T]))
		case 13:
			return unsafe.Pointer(new(ptrObject[T, [13]uint64, [51]T]))
		case 14:
			return unsafe.Pointer(new(ptrObject[T, [14]uint64, [50]T]))
		case 15:
			return unsafe.Pointer(new(ptrObject[T, [15]uint64, [49]T]))
		case 16:
			return unsafe.Pointer(new(ptrObject[T, [16]uint64, [48]T]))
		case 17:
			return unsafe.Pointer(new(ptrObject[T, [17]uint64, [47]T]))
		case 18:
			return unsafe.Pointer(new(ptrObject[T, [18]uint64, [46]T]))
		case 19:
			return unsafe.Pointer(new(ptrObject[T, [19]uint64, [45]T]))
		case 20:
			return unsafe.Pointer(new(ptrObject[T, [20]uint64, [44]T]))
		case 21:
			return unsafe.Pointer(new(ptrObject[T, [21]uint64, [43]T]))
		case 22:
			return unsafe.Pointer(new(ptrObject[T, [22]uint64, [42]T]))
		case 23:
			return unsafe.Pointer(new(ptrObject[T, [23]uint64, [41]T]))
		case 24:
			return unsafe.Pointer(new(ptrObject[T, [24]uint64, [40]T]))
		case 25:
			return unsafe.Pointer(new(ptrObject[T, [25]uint64, [39]T]))
		case 26:
			return unsafe.Pointer(new(ptrObject[T, [26]uint64, [38]T]))
		case 27:
			return unsafe.Pointer(new(ptrObject[T, [27]uint64, [37]T]))
		case 28:
			return unsafe.Pointer(new(ptrObject[T, [28]uint64, [36]T]))
		case 29:
			return unsafe.Pointer(new(ptrObject[T, [29]uint64, [35]T]))
		case 30:
			return unsafe.Pointer(new(ptrObject[T, [30]uint64, [34]T]))
		case 31:
			return unsafe.Pointer(new(ptrObject[T, [31]uint64, [33]T]))
		case 32:
			return unsafe.Pointer(new(ptrObject[T, [32]uint64, [32]T]))
		case 33:
			return unsafe.Pointer(new(ptrObject[T, [33]uint64, [31]T]))
		case 34:
			return unsafe.Pointer(new(ptrObject[T, [34]uint64, [30]T]))
		case 35:
			return unsafe.Pointer(new(ptrObject[T, [35]uint64, [29]T]))
		case 36:
			return unsafe.Pointer(new(ptrObject[T, [36]uint64, [28]T]))
		case 37:
			return unsafe.Pointer(new(ptrObject[T, [37]uint64, [27]T]))
		case 38:
			return unsafe.Pointer(new(ptrObject[T, [38]uint64, [26]T]))
		case 39:
			return unsafe.Pointer(new(ptrObject[T, [39]uint64, [25]T]))
		case 40:
			return unsafe.Pointer(new(ptrObject[T, [40]uint64, [24]T]))
		case 41:
			return unsafe.Pointer(new(ptrObject[T, [41]uint64, [23]T]))
		case 42:
			return unsafe.Pointer(new(ptrObject[T, [42]uint64, [22]T]))
		case 43:
			return unsafe.Pointer(new(ptrObject[T, [43]uint64, [21]T]))
		case 44:
			return unsafe.Pointer(new(ptrObject[T, [44]uint64, [20]T]))
		case 45:
			return unsafe.Pointer(new(ptrObject[T, [45]uint64, [19]T]))
		case 46:
			return unsafe.Pointer(new(ptrObject[T, [46]uint64, [18]T]))
		case 47:
			return unsafe.Pointer(new(ptrObject[T, [47]uint64, [17]T]))
		case 48:
			return unsafe.Pointer(new(ptrObject[T, [48]uint64, [16]T]))
		case 49:
			return unsafe.Pointer(new(ptrObject[T, [49]uint64, [15]T]))
		case 50:
			return unsafe.Pointer(new(ptrObject[T, [50]uint64, [14]T]))
		case 51:
			return unsafe.Pointer(new(ptrObject[T, [51]uint64, [13]T]))
		case 52:
			return unsafe.Pointer(new(ptrObject[T, [52]uint64, [12]T]))
		case 53:
			return unsafe.Pointer(new(ptrObject[T, [53]uint64, [11]T]))
		case 54:
			return unsafe.Pointer(new(ptrObject[T, [54]uint64, [10]T]))
		case 55:
			return unsafe.Pointer(new(ptrObject[T, [55]uint64, [9]T]))
		case 56:
			return unsafe.Pointer(new(ptrObject[T, [56]uint64, [8]T]))
		case 57:
			return unsafe.Pointer(new(ptrObject[T, [57]uint64, [7]T]))
		case 58:
			return unsafe.Pointer(new(ptrObject[T, [58]uint64, [6]T]))
		case 59:
			return unsafe.Pointer(new(ptrObject[T, [59]uint64, [5]T]))
		case 60:
			return unsafe.Pointer(new(ptrObject[T, [60]uint64, [4]T]))
		case 61:
			return unsafe.Pointer(new(ptrObject[T, [61]uint64, [3]T]))
		case 62:
			return unsafe.Pointer(new(ptrObject[T, [62]uint64, [2]T]))
		case 63:
			return unsafe.Pointer(new(ptrObject[T, [63]uint64, [1]T]))
		}
	}
	return nil
}
